### PR TITLE
fixed the bug about dynamic pages, dropped jQuery, added gulp & bower support

### PR DESCRIPTION
**Pull request by kivancsahici**
Hello Timo,

Thanks again for creating this useful pugin!

I noticed that the plugin does not work if the programmer adds dynamic pages to the view using Router API. I fixed that and also I added **gulp** and **bower** support to the plugin. Therefore, I had to re-work the directory structure a bit. And finally, I dropped the **jQuery** dependency from the plugin so it works directly with Dom7 API.

Happy coding :)

### CODE REVIEW

**Comment by valnub** [comment]
I tried your demo but it doesn't work (gives lots of JavaScript errors). Seems like it cannot find F7 lib. Please fix. Tested on Google Chrome Desktop browser.

bildschirmfoto 2015-10-05 um 15 03 55

**Comment by kivancsahici** [comment]
Oh, sorry. I have forgotten to mention bower dependency installation step.

To check the demo directly from the repository, you should first go to demo folder and execute in terminal bower install.

I also updated README about this.

**Comment by valnub** [comment]
Jep, that did the trick

**Comment by valnub** [comment]
There is also a bower file in the root directory. What's that for?

**Comment by kivancsahici** [comment]
That's good for adding this plug-in, itself to bower repo. This will make it possible for other people to add upscroller plugin to their projects easily.

But of course, we should also push upscroller plugin to bower repo. Once the pull request is merged, I can do that, too.

**Comment by valnub** [comment]
Thanks looks all good, I merged the PR.

**Comment by kivancsahici** [comment]
Thanks! I just found a typo in bower.json file. It was causing a json parse error and upscroller plugin was being rejected by bower. Therefore, I fixed the typo and pushed it again .

I think I have to create another pull request. I guess github does not support reopen feature for the already closed PR.

**Comment by valnub** [comment]
Ah, yes. The tricky sneaky trailing colon :)
I recommend Brackets with jsLint to find such errors while coding.
PR is merged.

**Pull request merged**
